### ISSUE TITLE
Issue in Arduinomenu

### ISSUE THREAD

**Issue by hicksan** [neu-rah/tinyTimeUtils#1]
Hi Rui, Please could you take a look at the issue I raised in ArduinoMenu? I've had C++ experts looking into it and they say the data structures are too complex to figure out. I don't want to give up. All it is is getting u8g2 library to work when MENU_USERAM is defined. It works in part but not when drawing menu items, because the data structure is changed to store the data in a different way, so I get garbage instead. Thanks very much. It's such a fantastic library but I have tried everything and still can't get it to work.

**Comment by neu-rah** [comment]
sorry fir the long time
